#!/usr/local/bin/python2.7

##Script for getting total weighted methylation levels from a genome using an allc file generated by Methylpy.

import sys
import getopt
import math

def main(argv):
	input = argv[0] ##input allc file
	output = argv[1] ##output allc file
	
	f = open(input)
	next(f)
	
	CG = 0
	mCG = 0
	CHG = 0
	mCHG = 0
	CHH = 0
	mCHH = 0
	
	for l in f:
		per_row =  l.split("\t")
		if str(per_row[3]) == "CGA" or str(per_row[3]) == "CGT" or str(per_row[3]) == "CGC" or str(per_row[3]) == "CGG" or str(per_row[3]) == "CGN" or str(per_row[3]) == "CG":
			CG = CG + int(per_row[5])
			mCG = mCG + int(per_row[4])
		elif str(per_row[3]) == "CAG" or str(per_row[3]) == "CCG" or str(per_row[3]) == "CTG" or str(per_row[3]) == "CHG":
			CHG = CHG + int(per_row[5])
			mCHG = mCHG + int(per_row[4])
		elif str(per_row[3]) == "CAA" or str(per_row[3]) == "CAT" or str(per_row[3]) == "CAC" or str(per_row[3]) == "CTA" or str(per_row[3]) == "CTC" or str(per_row[3]) == "CTT" or str(per_row[3]) == "CCA" or str(per_row[3]) == "CCT" or str(per_row[3]) == "CCC" or str(per_row[3]) == "CHH":
			CHH = CHH + int(per_row[5])
			mCHH = mCHH + int(per_row[4])
	
	f.close()
	
	pCG = float(mCG)/float(CG)
	pCHG = float(mCHG)/float(CHG)
	pCHH = float(mCHH)/float(CHH)
	
	out = open(output, "w")
	
	out.write("Total_CG" + "\t" + "Methy_CG" + "\t" + "Percent_Methyl_CG" + "\t" + "Total_CHG" + "\t" + "Methy_CHG" + "\t" + "Percent_Methyl_CHG" + "\t" + "Total_CHH" + "\t" + "Methy_CHH" + "\t" + "Percent_Methyl_CHH" + "\n")
	out.write(str(CG) + "\t" + str(mCG) + "\t" + str(pCG) + "\t" + str(CHG) + "\t" + str(mCHG) + "\t" + str(pCHG) + "\t" + str(CHH) + "\t" + str(mCHH) + "\t" + str(pCHH) + "\n")
	
	out.close()
	
if __name__ == "__main__":
   main(sys.argv[1:])
